version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - run: echo "build job"
  deploy:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - run: echo "deploy job"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
    triggers:
        - schedule:
            cron: "0,30 * * * *"
            filters:
              branches:
                  only:
                    - sleep


