executors:
  default: # デフォルトのDockerイメージ
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

version: 2.1
jobs:
  checkout_code: # ソースコードを取得
    executor: default
    steps:
      - checkout
      - save_cache: # ソースコードをキャッシュ。キーはリポジトリの最終コミットのハッシュ
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  node_dependencies:
    executor: default
    steps:
      - restore_cache: # ソースコードを復元
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # Yarnキャッシュを復元
          key: v1-yarn-{{ checksum "yarn.lock" }}-{{ arch }}
      - run:
          name: Yarn Install
          command: yarn install
      - save_cache: # Yarnキャッシュをキャッシュ
          key: v1-yarn-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

  node_dependencies_with_node_modules:
    executor: default
    steps:
      - restore_cache: # ソースコードを復元
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache: # Yarnキャッシュを復元
          key: v1-yarn-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache: # node_modulesを復元
          key: v1-node-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Yarn Install
          command: yarn install
      - save_cache: # Yarnキャッシュをキャッシュ
          key: v1-yarn-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache: # node_modulesをキャッシュ
          key: v1-node-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - node_dependencies: # checkout_codeのあとに実行
          requires:
            - checkout_code
      - node_dependencies_with_node_modules:
          requires:
            - checkout_code
